### ISSUE TITLE
Please evaluate cooperation with GSOC 2013 opencv tracking API/benchmark efforts

### ISSUE THREAD

**Issue by bhack** [vicoslab/legit#1]
https://github.com/Itseez/opencv_contrib/tree/master/modules/tracking

**Comment by lukacu** [comment]
What do you mean by evaluation of cooperation? Are you involved in the GSoC 2013 OpenCV? I have no problem with cooperation for common OpenCV tracking API (that would be great), however, my performance evaluation efforts are currently focused on [VOT challenge](http://votchallenge.net/index.html) and the [VOT evaluation kit](https://github.com/vicoslab/vot-toolkit).

**Comment by lenlen** [comment]
Hi @lukacu , I have developed this tracking API for OpenCV library in the GSoC 2013 and I have ported two algorithms: MIL and Boosting.
During the current GSoC another algorithm (LTD) is been integrated in the API.
Also, the tracking API has a test framework based on Google Test that you can find in test folder of the module. It is partially based on this work [1]. 
These tests are very similar to VOT performance measures, experiment 1 is similar to OPE and experiment 2 is similar to SRE.
Maybe we can evaluate a cooperation with a possible integration of test metodologies, what do you think about?

[1] Y. Wu, J. Lim, and M.-H. Yang, "Online object tracking: A benchmark," in Computer Vision and Pattern Recognition (CVPR), 2013, https://sites.google.com/site/trackerbenchmark/benchmarks/v10

**Comment by lukacu** [comment]
Sure, that would be great. But I think we should get this discussion away from issue thread. You can find my contact information here: http://www.vicos.si/lukacu/ . As for the evaluation measures: there are some major differences of VOT in relation to [1] that we can also discuss.

**Comment by lukacu** [comment]
This conversation was now moved to an email correspondence. We are discussing a possible collaboration between OpenCV and VOT. I am closing the issue.
